backend:
  name: git-gateway
  # Use a separate branch for publishing activity by the user
  branch: publishing
# Path for media storage
media_folder: public/img
# Path to media storage for the published website
public_folder: img
# Saved posts pushes a commit directly
# publish_mode: editorial_workflow
collections:
  - name: pages   # Used in routes, e.g., /admin/collections/pages
    label: Pages  # Used in the UI
    files:
    - label: Home
      name: home
      file: content/home.md
      fields:
        - label: Hero
          name: hero
          widget: object
          fields:
            - label: Title
              name: title
              widget: string
              
            - label: Headings
              name: headings 
              widget: list      # List of headings
              allow_add: true   # Allow user to add or remove number of headings,
              min: 1
              max: 3
              field: { label: Value, name: value, widget: string }

            - label: Body
              name: body
              widget: markdown 

            - label: Call to Actions
              name: buttons
              widget: list    
              allow_add: true 
              min: 1
              max: 2
              fields: 
                - { label: Value, name: value, widget: string }
                - { label: Link, name: link, widget: string }
