backend:
  # name: git-gateway
  name: test-repo
  # Use a separate branch for publishing activity by the user
  branch: publishing
# Path for media storage
media_folder: public/img
# Path to media storage for the published website
public_folder: img
# Saved posts pushes a commit directly
# publish_mode: editorial_workflow
collections:
  - name: pages   # Used in routes, e.g., /admin/collections/pages
    label: Pages  # Used in the UI
    files:
    - label: Home
      name: home
      file: content/home.md
      fields:
        - label: Hero
          name: hero
          widget: object
          fields:
            - label: Title
              name: title
              widget: string
              hint: This is the title shown in the tab in a user's browser.

            - label: Headings
              name: headings 
              widget: list      # List of headings
              allow_add: true   # Allow user to add or remove number of headings,
              min: 1
              max: 3
              field: { label: Text, name: text, widget: string }
              hint: The main headers shown on the hero of the landing page.

            - label: Body
              name: body
              widget: markdown 
              hint: The main body text on the hero under the headers of the landing page.

            - label: Call to Actions
              name: buttons
              widget: list    
              allow_add: true
              required: false
              max: 2
              hint: Optional buttons that a user can click to redirect to another page.
              fields: 
                - label: Text
                  name: text
                  widget: string
                - label: Link
                  name: link
                  widget: string
                  hint: The link path must be in the format of "/path-of-page"
